<?php
require_once __DIR__ . '/_helpers.php';
auth_require_module_modify('horarios'); auth_validate_csrf();
try {
    $data=horarios_input();$id=(int)($data['id']??0);$row=horarios_payload($data);$from=horarios_text($data['fecha_inicio']??'',10);$to=horarios_text($data['fecha_fin']??'',10);
    if(!horarios_date_valid($from)||!horarios_date_valid($to)||$to<$from)horarios_json(false,'Selecciona un rango de fechas válido.',[],422);
    $start=new DateTime($from);$end=new DateTime($to);if((int)$start->diff($end)->format('%a')>366)horarios_json(false,'El rango no puede superar un año.',[],422);
    $target=$pdo->prepare("SELECT serie_id FROM horarios_medicos WHERE id=:id LIMIT 1");$target->execute([':id'=>$id]);$series=(string)$target->fetchColumn();if($series==='')horarios_json(false,'No se encontró la programación grupal.',[],404);
    $byDay=[];$input=is_array($data['dias_horarios']??null)?$data['dias_horarios']:[];foreach($input as $schedule){$day=(int)($schedule['dia']??0);$fromTime=horarios_text($schedule['hora_inicio']??'',5);$toTime=horarios_text($schedule['hora_fin']??'',5);if($day<1||$day>7||!horarios_time_valid($fromTime)||!horarios_time_valid($toTime)||$toTime<=$fromTime)horarios_json(false,'Revisa los días y sus horas de atención.',[],422);$byDay[$day][]=[$fromTime,$toTime];}
    if(!$byDay)horarios_json(false,'Selecciona al menos un día de atención.',[],422);foreach($byDay as &$blocks){usort($blocks,function($a,$b){return strcmp($a[0],$b[0]);});for($i=1,$n=count($blocks);$i<$n;$i++)if($blocks[$i][0]<$blocks[$i-1][1])horarios_json(false,'Un mismo día contiene horarios superpuestos.',[],422);}unset($blocks);
    $dates=[];for($date=clone $start;$date<=$end;$date->modify('+1 day')){$day=(int)$date->format('N');if(isset($byDay[$day]))foreach($byDay[$day] as $block)$dates[]=[$date->format('Y-m-d'),$block[0],$block[1]];}if(!$dates)horarios_json(false,'El rango no contiene los días seleccionados.',[],422);
    $pdo->beginTransaction();horarios_sync_doctor_color($pdo,$row);$pdo->prepare("DELETE FROM horarios_medicos WHERE serie_id=:serie")->execute([':serie'=>$series]);
    $sql="INSERT INTO horarios_medicos (serie_id,medico_id,especialidad_id,medico,especialidad,rama,fecha,hora_inicio,hora_fin,modalidad,tipo_atencion,estado,publicacion,cupos_totales,cupos_ocupados,observaciones,color,creado_por,actualizado_por) VALUES (:serie,:medico_id,:especialidad_id,:medico,:especialidad,:rama,:fecha,:inicio,:fin,:modalidad,:tipo,:estado,:publicacion,0,0,:observaciones,:color,:usuario,:usuario_actualiza)";$stmt=$pdo->prepare($sql);
    foreach($dates as $date)$stmt->execute([':serie'=>$series,':medico_id'=>$row['medico_id'],':especialidad_id'=>$row['especialidad_id'],':medico'=>$row['medico'],':especialidad'=>$row['especialidad'],':rama'=>$row['rama']?:null,':fecha'=>$date[0],':inicio'=>$date[1],':fin'=>$date[2],':modalidad'=>$row['modalidad'],':tipo'=>$row['tipo_atencion'],':estado'=>$row['estado'],':publicacion'=>$row['publicacion'],':observaciones'=>$row['observaciones']?:null,':color'=>$row['color'],':usuario'=>auth_user_id(),':usuario_actualiza'=>auth_user_id()]);
    $pdo->commit();auth_audit($pdo,'programacion_actualizada',auth_user_id(),auth_username(),count($dates).' horario(s) para '.$row['medico']);horarios_json(true,'Programación completa actualizada.',['updated'=>count($dates)]);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('Error actualizando serie: '.$e->getMessage());horarios_json(false,'No se pudo actualizar la programación completa.',[],500);}
