<?php require_once __DIR__.'/templates/header.php';$canModify=auth_can_modify_module('medicos'); ?>
<link rel="stylesheet" href="assets/css/medicos-alignment.css?v=1.0">
<main class="container doctors-page">
 <section class="panel doctors-hero"><div><span class="dashboard-label">Centro médico</span><h1>Directorio de profesionales</h1><p>Información centralizada de profesionales, especialidades y horarios vinculados.</p></div><?php if($canModify):?><button class="btn-primary" id="newDoctorBtn">+ Nuevo profesional</button><?php endif;?></section>
 <section class="doctor-stats"><article><span>Profesionales</span><strong id="doctorCount">0</strong></article><article><span>Activos</span><strong id="activeDoctorCount">0</strong></article><article><span>Especialidades</span><strong id="specialtyCount">0</strong></article></section>
 <section class="panel doctors-toolbar"><div class="doctor-tabs"><button class="is-active" data-doctor-tab="professionals">Profesionales</button><button data-doctor-tab="specialties">Especialidades y ramas</button></div><label class="doctor-search"><span>Buscar</span><input id="doctorSearch" placeholder="Escribe un nombre o especialidad"></label></section>
 <section class="panel" id="professionalsPanel"><div class="panel-title"><div><h2>Profesionales de IPHCI</h2><p>Listado organizado por especialidad principal para encontrar cada profesional con rapidez.</p></div></div><div class="doctor-specialty-groups" id="doctorGroups"></div></section>
 <section class="panel hidden" id="specialtiesPanel"><div class="panel-title"><div><h2>Especialidades y ramas</h2><p>Catálogo utilizado en Médicos y Horarios.</p></div><?php if($canModify):?><button class="btn-secondary" id="newSpecialtyBtn">+ Nueva especialidad</button><?php endif;?></div><div class="specialty-grid" id="specialtyGrid"></div></section>
</main>
<?php if($canModify):?>
<div class="doctor-modal hidden" id="doctorModal"><div class="doctor-modal__backdrop" data-close-doctor></div><form class="doctor-modal__dialog" id="doctorForm"><div class="doctor-modal__header"><div><p>Directorio IPHCI</p><h2 id="doctorModalTitle">Nuevo profesional</h2></div><button type="button" data-close-doctor>×</button></div><input type="hidden" id="doctorId"><div class="doctor-form-grid"><label class="wide"><span>Nombre completo *</span><input id="doctorName" required placeholder="Ej. Dr. José Delgado"></label><label><span>Estado</span><select id="doctorStatus"><option>Activo</option><option>Temporalmente no disponible</option><option>Inactivo</option></select></label><label><span>Color en el calendario</span><span class="doctor-color-field"><input type="color" id="doctorColor" value="#5b21b6"><output id="doctorColorValue">#5b21b6</output></span></label><label class="wide"><span>Especialidad principal *</span><select id="primarySpecialty"></select></label><div class="wide specialty-picker"><label><span>Buscar y añadir especialidades</span><input id="specialtyPickerSearch" placeholder="Ej. cli para Cardiología clínica" autocomplete="off"></label><div class="specialty-picker__options" id="specialtyPickerOptions"></div><div class="specialty-picker__selected" id="selectedSpecialties"></div></div><label class="wide"><span>Observaciones internas</span><textarea id="doctorNotes" rows="3"></textarea></label></div><div class="doctor-modal__actions"><button type="button" class="btn-secondary" data-close-doctor>Cancelar</button><button class="btn-primary">Guardar profesional</button></div></form></div>
<div class="doctor-modal hidden" id="specialtyModal"><div class="doctor-modal__backdrop" data-close-specialty></div><form class="doctor-modal__dialog doctor-modal__dialog--small" id="specialtyForm"><div class="doctor-modal__header"><div><p>Catálogo</p><h2 id="specialtyModalTitle">Nueva especialidad</h2></div><button type="button" data-close-specialty>×</button></div><input type="hidden" id="specialtyId"><label><span>Nombre de la especialidad o rama</span><input id="specialtyName" required placeholder="Ej. Cardiología clínica"></label><div class="doctor-modal__actions"><button type="button" class="btn-secondary" data-close-specialty>Cancelar</button><button class="btn-primary">Guardar</button></div></form></div>
<?php endif;?>
<script>window.DOCTORS_CAN_MODIFY=<?=$canModify?'true':'false'?>;</script><script src="assets/js/medicos.js?v=3.1"></script>
<?php require_once __DIR__.'/templates/footer.php';?>
